default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: csc+394+2014

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

production:
  <<: *default
  database: prod
